server:
  port: 0
spring:
  application:
    name: etc-service
  cloud:
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource
    client:
      hostname: localhost
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/orai?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id}:${random.value}}
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    #path: /api/mail/v3/api-docs
    # ????? ????? prefix? ???? ???? ?? ??? ??
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# ????? ?? (beans: ????? ??? ? ???. health: ?? ????? ???)
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans